name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: arm-none-eabi-gcc
    - uses: fiam/arm-none-eabi-gcc@v1
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
