name: Build

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Get required packages
    - uses: actions/checkout@v2
    - uses: fiam/arm-none-eabi-gcc@v1
      with:
        release: '10-2021-q4'

    # Build with make
    - name: make
      env: 
        VARIANT: VARIANT_DEBUG
      run: make

