name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: arm-none-eabi-gcc
    - uses: fiam/arm-none-eabi-gcc@v1
      with:
      release: '9-2019-q4' # The arm-none-eabi-gcc release to use.
    - run: make
    
